# backend:
#   name: github
#   repo: "Wakan-Dojo/website"
#   branch: main

local_backend: true
backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: gatsby

media_folder: static

media_library:
  name: cloudinary
  config:
    cloud_name: do5ihi4vp
    api_key: 756368395847219
    output_filename_only: true

collections:
  - name: "metadata"
    label: "Metadata"
    files:
      - name: "metadata"
        label: "Metadata"
        file: "content/metadata.yml"
        fields:
          - label: "Titre du site"
            name: "title"
            widget: "string"
          - label: "Sous-titre du site"
            name: "subtitle"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
            hint: "Description du site, utilisée pour le référencement SEO"
          - label: "Mots-clés SEO"
            name: "keywords"
            widget: "string"
            hint: "Mots-clés utilisés pour le référencement SEO, séparés par des virgules"
          - label: "Social card"
            name: "social_card"
            widget: "image"
            hint: "Cette image sera affichée quand le site est partagé sur les réseaux sociaux"

          - label: "URL"
            name: "url"
            hint: "URL de déploiement du site"
            widget: "string"
            pattern: ["https://.*", "Ce champ doit être une URL"]

          - label: "Social Icons"
            name: "social_icons"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Icon"
                name: "icon"
                widget: "string"
                hint: "Nom de l'icône, tiré de https://simpleicons.org/"

              - label: "Href"
                name: "href"
                widget: "string"
                pattern: ["https://.*", "Ce champ doit être une URL"]
