name: Deploy
on:
  push:
    branches:
      - 'zip'
      
jobs:
  build:

    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Unzip archive
        run: |
          unzip site.zip
          rm site.zip
        
      - name: Publish to "publish" branch
        run: |
          git checkout -b tmp
          git add .
          git commit -m "New version from zip"
          git checkout publish
          git reset --hard tmp
          git push --force origin publish
